services:
  dash-api:
    build: ./server
    container_name: enclave-api
    restart: always
    expose:
      - "3005"
    volumes:
      - /:/host:ro
      - /home/ubuntu:/data
      - /home/ubuntu/projects:/app/projects
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env
    networks:
      - proxy

  dash-ui:
    build:
      context: ./client
      args:
        VITE_API_DOMAIN: ""
        VITE_DASHBOARD_DOMAIN: ${VITE_DASHBOARD_DOMAIN}
    container_name: enclave-ui
    restart: always
    expose:
      - "5173"
    depends_on:
      - dash-api
    env_file: .env
    networks:
      - proxy

networks:
  proxy:
    external: true
