services:
  dash-api:
    build: ./server
    container_name: enclave-api
    restart: always
    ports:
      - "3005:3005"
    volumes:
      - /:/host:ro # System Monitoring
      - /home/ubuntu/projects:/app/projects # Terminal workspace
    env_file: .env

  dash-ui:
    build: ./client
    container_name: enclave-ui
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - dash-api
    env_file: .env